config/config.go, config/config_test.go
=> fix producer topic name

config/config.go, config/config_test.go
Remote HTTP protocol from Kafka address.
=> Remote HTTP protocol from Kafka address. 

dp-observation-extractor.nomad
Fix artifacts.
@LloydGriffiths
=> Fix artifacts.

cmd/dp-observation-extractor/main.go
Add missing dependencies to vendor so repo will build on CI
Make sure vendor contains correct things
Anyone but me
=> Fix import from pkg/errors to std lib

README.md
I clicked merge on github again...
=> minor change to read me to get a signed commit

vendor/github.com/ONSdigital/go-ns/kafka/consumer-group.go, vendor/vendor.json
Use updated kafka lib with indefinite offset retention
=> Use updated kafka lib with indefinite offset retention

config/config.go, config/config_test.go
=> Enable encryption by default

README.md
Update readme
Verify it makes sense
Anyone
=> Update README with aws credential configuration

cmd/dp-observation-extractor/main.go, vendor/github.com/ONSdigital/s3crypto/s3crypto.go, vendor/github.com/aws/aws-sdk-go/aws/config.go, vendor/github.com/aws/aws-sdk-go/aws/types.go, vendor/github.com/aws/aws-sdk-go/aws/version.go, vendor/github.com/aws/aws-sdk-go/internal/sdkio/io_go1.6.go, vendor/github.com/aws/aws-sdk-go/internal/sdkio/io_go1.7.go, vendor/github.com/aws/aws-sdk-go/internal/sdkrand/locked_source.go, vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/batch.go, vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/bucket_region.go, vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/doc.go, vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go, vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go, vendor/vendor.json
Update s3crypto lib
Verify logic correct
Anyone
=> Update s3crypto library to fix encryption

event/consumer.go, event/csv_handler.go
Not enough logging/difficult to debug
check changes wont cause more problems
anyone
=> Add log line to check if a file has been read from S3

event/csv_handler.go
Add logging around getting vault key / s3 file
=> Add logging around getting vault key / s3 file

vendor/github.com/ONSdigital/s3crypto/s3crypto.go, vendor/vendor.json
Update s3crypto
Verify its updated
Anyone
=> Update s3crypto to avoid reading whole file into memory

vendor/github.com/ONSdigital/s3crypto/s3crypto.go, vendor/vendor.json
=> Update s3crypto vendor

vendor/github.com/ONSdigital/s3crypto/s3crypto.go, vendor/vendor.json
Update s3crypto so decryption is done when Reader is called (avoids loading full file into memory)
=> Update s3crypto to decrypt on read

dp-observation-extractor.nomad
Using docker reduces the likelihood of timeout on deploy
check for typos
check repo names are consistent
check web/publishing both updated
anyone
=> Update nomad plan to use docker instead of exec driver

dp-observation-extractor.nomad
What
Fix smart for double quotes
How to review
check quotes are not crazy
Who can review
anyone
=> Fix smart for double quotes

LICENSE.md
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
=> Update licence and trigger build

README.md
new year in readme
approve of the year
you, please
=> update year in README - trigger build

Makefile, ci/audit.yml, ci/scripts/audit.sh
Added dependency auditing to observation extractor
Check changes make sense and auditing works `make audit`
Anyone
=> Add dependency auditing

cmd/dp-observation-extractor/main.go, service/service.go
We have extracted the main application code into service.go so that we can call service.Run() as an entry point for the component-test, the services are injected so that they can be controlled from the test.
Needs to be approved before we can start with the actual component-test branch
Run the application and check it behaves as it did before
=> refactor main script into service package
